name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          fetch-depth: 0

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: 24
          cache: true

      - name: Install dependencies
        run: vp install

      - name: Build packages
        run: vp run -r build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@06245a4e0a36c463a9308ffd6a9de192a3d00b48 # v4
        with:
          publish: vp run publish-packages
          version: vp run version-packages
          commit: 'chore: release packages'
          title: 'chore: release packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
